#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Override PHP binary to use wrapper script (fixes spaces in path)
$wrapperPath = __DIR__ . '/php-wrapper';
if (file_exists($wrapperPath)) {
    putenv('PHP_BINARY=' . $wrapperPath);
    $_ENV['PHP_BINARY'] = $wrapperPath;
    $_SERVER['PHP_BINARY'] = $wrapperPath;
}

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
